kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30100
        hostPort: 8443
        listenAddress: "0.0.0.0"
        protocol: TCP
    image: kindest/node:v1.25.0-beta.0
